
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ID IF INT LE PP WHILE\n    E : E '+' T\n      | T\n    \n    T : T '*' F\n      | F\n    \n    F : '(' E ')'\n    \n    F : INT\n    "
    
_lr_action_items = {'(':([0,4,6,7,],[4,4,4,4,]),'INT':([0,4,6,7,],[5,5,5,5,]),'$end':([1,2,3,5,9,10,11,],[0,-2,-4,-6,-1,-3,-5,]),'+':([1,2,3,5,8,9,10,11,],[6,-2,-4,-6,6,-1,-3,-5,]),')':([2,3,5,8,9,10,11,],[-2,-4,-6,11,-1,-3,-5,]),'*':([2,3,5,9,10,11,],[7,-4,-6,7,-3,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'E':([0,4,],[1,8,]),'T':([0,4,6,],[2,2,9,]),'F':([0,4,6,7,],[3,3,3,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> E","S'",1,None,None,None),
  ('E -> E + T','E',3,'p_E','scanner.py',56),
  ('E -> T','E',1,'p_E','scanner.py',57),
  ('T -> T * F','T',3,'p_T','scanner.py',66),
  ('T -> F','T',1,'p_T','scanner.py',67),
  ('F -> ( E )','F',3,'p_F_with_parentheses','scanner.py',76),
  ('F -> INT','F',1,'p_F_integer','scanner.py',82),
]
